#!/bin/bash
export IMAGIC_BATCH=1
# Batch assumes that you used prep_conic3.b to prepare your files for Imagic alignment
echo "Batch to convert Xmipp3 parameters to Imagic"
echo "Last alined untilted imagic file: "
Ali=`zenity --file-selection --title="Last alined untilted imagic file" --file-filter=*.img`
echo "Centered tilted imagic file: "
Tilt=`zenity --file-selection --title="Centered tilted imagic file" --file-filter=*.img`
/home/imagic/imagic_110308_64/stand/headers.e <<EOF >/dev/null
PLT
INDEX
NUM
116
NO
$Ali
gamma_plus.plt
EOF
#Reverse gamma angles:
cat gamma_plus.plt | awk '{print -$1}' > gamma.plt
rm -f gamma_plus.plt
if du | grep "Images/Extracted" > /dev/null
then :
else
echo "You didn't run Particle extraction!" && exit 1
fi
echo -en "Hit enter to select the micrographs.xmd file"
read Junk1
Xmd=`zenity --file-selection --title="micrographs.xmd file" --file-filter=*.xmd`
[ -f alpha.plt ] && rm -f alpha.plt
[ -f beta.plt ] && rm -f beta.plt
# xmipp: imagic_alpha=alpha_t+90
/home/platform/relion1.2/bin/relion_star_printtable $Xmd data_micrographPairs _micrograph _angleY2 _angleTilt | awk '{print $1,$2+90,$3}' > angles.plt
cut -d" " -f1 angles.plt | sed 's/[^0-9]*//g;s/^0*//' > del.plt
cut -d" " -f2,3 angles.plt > del2.plt
paste -d ' ' del.plt del2.plt > angles.plt
rm -f del.plt del2.plt
/home/imagic/imagic_110308_64/stand/headers.e <<EOF >/dev/null
PLT
INDEX
NUM
52
NO
$Ali
mic_num.plt
EOF
cat mic_num.plt | cut -d'.' -f1 | sed 's/[^0-9]*//g' > mic_num2.plt
for key in `cat mic_num2.plt`;
do
awk -v key=$key '($1==key)' angles.plt >> del3.plt;
done
cut -d" " -f2 del3.plt > alpha.plt
cut -d" " -f3 del3.plt > beta.plt
rm -f del3.plt mic_num.plt mic_num2.plt
/home/imagic/imagic_110308_64/stand/headers.e <<EOF >/dev/null
WRITE
INDEX
NUM
65
FILE
alpha.plt
$Tilt
EOF
/home/imagic/imagic_110308_64/stand/headers.e <<EOF >/dev/null
WRITE
INDEX
NUM
66
FILE
beta.plt
$Tilt
EOF
/home/imagic/imagic_110308_64/stand/headers.e <<EOF >/dev/null
WRITE
INDEX
NUM
67
FILE
gamma.plt
$Tilt
EOF
/home/imagic/imagic_110308_64/stand/headers.e <<EOF >/dev/null
TAKE_OVER
AR_EULER_TO_PM_EULER
$Tilt
EOF
